service: eCommerceChapter04ExamplesAlexa

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  memorySize: 1024

functions:
  function1:
    handler: src/function1.handler
    events:
      # use an existing Alexa Skill ARN
      - alexaSmartHome: amzn1.ask.skill.12-34-56-78
  function2:
    handler: src/function2.handler
    events:
      # use an existing Alexa Smart Home Skill ARN
      - alexaSmartHome: amzn1.ask.skill.98-76-54-32
