service: eCommerceChapter04ExamplesCloudWatchLogs

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  memorySize: 1024

functions:
  function1:
    handler: src/function1.handler
    events:
      - cloudwatchLog:
          logGroup: '/aws/lambda/eCommerceChapter04ExamplesApiGateway-dev-function1'
          filter: '{$.queryStringParameters.testKey = testValue}'
  function2:
    handler: src/function2.handler
    events:
      - cloudwatchLog: '/aws/api-gateway/eCommerceChapter04ExamplesApiGateway-dev'
