service: eCommerceChapter04ExamplesIoT

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  memorySize: 1024

functions:
  function1:
    handler: src/function1.handler
    events:
      - iot:
          name: 'iotErrors'
          sql: "SELECT * FROM 'iot/errors'"
          description: 'IoT errors topic'