service: ssbook-ch10-apigw

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  memorySize: 1024
  logRetentionInDays: 1
  logs:
    restApi:
      accessLogging: true
      format: 'requestId: $context.requestId'
      executionLogging: true
      level: INFO
      fullExecutionData: false

functions:
  myFunction:
    handler: myFunction.handler
    awsKmsKeyArn: arn:aws:kms:us-east-1:123456789012:key/aa000a00-a0aa-0a00-000a-0000a00a1a11
    environment:
      SECRET_NAME: secretValue
    events:
      - http:
          path: myFunction
          method: get
          cors:
            origin: 'myservice.com'
            maxAge: 600
            allowCredentials: false
            cacheControl: 'max-age=600, s-maxage=600, proxy-revalidate, private'
  sensitiveData:
    handler: sensitiveData.handler
    awsKmsKeyArn: arn:aws:kms:us-east-1:123456789012:key/aa000a00-a0aa-0a00-000a-0000a00a1a11
    environment:
      SECRET_NAME: secretValue
    events:
      - http:
          path: sensitiveData
          method: get
          cors:
            origin: 'myservice.com'
            maxAge: 600
            allowCredentials: false
            cacheControl: 'no-cache, no-store, no-transform'
