service: ssbook-ch10-storage

provider:
  name: google
  stage: dev
  runtime: nodejs10
  region: us-central1
  project: serverlesssecuritybook
  credentials: ~/.gcloud/keyfile.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

resources:
  resources:
    - type: storage.v1.bucket
      name: my-serverless-service-bucket
    - name: myBucket
      type: gcs_bucket.py
      properties:
        name: myBucket
        location: us-east1
        versioning:
          enabled: True
  imports:
    - path: templates/gcs_bucket/gcs_bucket.py
      name: gcs_bucket.py