service: ssbook-ch10-functions

provider:
  name: google
  stage: dev
  runtime: nodejs10
  region: us-central1
  project: serverlesssecuritybook
  credentials: ~/.gcloud/keyfile.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  myFunction:
    handler: myFunction
    events:
      - http: path
