service: eCommerceChapter04ExamplesS3

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  memorySize: 1024

functions:
  function1:
    handler: src/function1.handler
    events:
      # create a new S3 bucket
      - s3:
          bucket: ${self:service}-${self:provider.stage}-products
          event: s3:ObjectCreated:*
          rules:
            - prefix: new/
            - suffix: .jpg
  function2:
    handler: src/function2.handler
    events:
      # use an existing S3 bucket
      - s3:
          bucket: ${self:service}-${self:provider.stage}-legacyProducts
          event: s3:ObjectRemoved:*
          existing: true